### ISSUE TITLE
instead of if/else, you could use ternary

### ISSUE THREAD

**Issue by dbqpll** [yurakiziuk/elevators#1]
https://github.com/yurakiziuk/elevators/blob/b6a19305c98fbfc30eeaecc2e8f6c3f407b99f29/src/system/Elevator.java#L20-L23
```java
this.capacity = capacity > CAPACITY_LIMIT ? 0 : capacity;

**Comment by yurakiziuk** [comment]
Thanks, got it. I'll replace it
